

services:
  sql-server:
    image: mcr.microsoft.com/azure-sql-edge:latest
    container_name: sentiance-db-local
    restart: always
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=SentianceLocal2026!
    ports:
      - "1433:1433"
    volumes:
      - sentiance_data:/var/opt/mssql
      - ./sql:/sql-scripts

volumes:
  sentiance_data:
